// <auto-generated />
using System;
using HelloWorldDemo.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HelloWorldDemo.Migrations
{
    [DbContext(typeof(RpsDBContext))]
    [Migration("20201224002738_migrations2")]
    partial class migrations2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("HelloWorldDemo.Model.Match", b =>
                {
                    b.Property<Guid>("MatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Player1PlayerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Player2PlayerID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MatchID");

                    b.HasIndex("Player1PlayerID");

                    b.HasIndex("Player2PlayerID");

                    b.ToTable("matches");
                });

            modelBuilder.Entity("HelloWorldDemo.Model.Player", b =>
                {
                    b.Property<Guid>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerID");

                    b.ToTable("players");
                });

            modelBuilder.Entity("HelloWorldDemo.Model.Round", b =>
                {
                    b.Property<Guid>("RoundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Player2Choice")
                        .HasColumnType("int");

                    b.Property<int>("PlayerChoice")
                        .HasColumnType("int");

                    b.Property<Guid?>("WinningPlayerPlayerID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoundID");

                    b.HasIndex("WinningPlayerPlayerID");

                    b.ToTable("rounds");
                });

            modelBuilder.Entity("HelloWorldDemo.Model.Match", b =>
                {
                    b.HasOne("HelloWorldDemo.Model.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1PlayerID");

                    b.HasOne("HelloWorldDemo.Model.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2PlayerID");

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });

            modelBuilder.Entity("HelloWorldDemo.Model.Round", b =>
                {
                    b.HasOne("HelloWorldDemo.Model.Player", "WinningPlayer")
                        .WithMany()
                        .HasForeignKey("WinningPlayerPlayerID");

                    b.Navigation("WinningPlayer");
                });
#pragma warning restore 612, 618
        }
    }
}
